### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by pachieh** [speedyg0nz/MagInkDash#4]
Running on a RaspPi Zero 2...

Every time I go to run main.py, it returns a KeyError: 'current' in line 22 of owm.py (curr_weather = data["current"]) which in turn causes issues in line 49 of main.py. 

If I leave 'self' in the get_owm_weather and get_weather definitions, it then gives errors for missing a positional argument when running main.py. 

I've tried reloading both main.py and owm.py with fresh copies but run also run into a ModuleNotFoundError for owm.owm; 'owm' is not a package.

No clue what's going on except things aren't working per your directions.

**Comment by SNTag** [comment]
I have the same issue. @pachieh did you resolve it?

Edit: it is an issue with the api! the url referenced under "owm/owm.py", function "get_owm_weather" requires a paid subscription.

Edit 2: the paid subscription appears to be free for the first 1K calls per day, but they need a card!

**Comment by pachieh** [comment]
I have not been able to resolve it yet @SNTag . I'll probably start looking at it again in a week or so and see what's going on.

**Comment by fdmarcin** [comment]
@pachieh @SNTag Hi! I took a stab at making this work and the script succeeds for me. Here's my fork https://github.com/fdmarcin/MagInkDash-updated

What needed to be changed:

- Code changed to work with the current OWM and OpenAI API's
- You need to add a payment method in both OWM and OpenAI. I also spent 5 USD to get into OpenAI Usage tier 1: https://platform.openai.com/settings/organization/limits

I also improved the README instructions in the fork.

Here's the image I generated yesterday:

![Image](https://github.com/user-attachments/assets/db18a65b-f45c-4d5f-b0f5-bbfbcf8345ea)

**Comment by pachieh** [comment]
@fdmarcin This has been supremely helpful, almost done on my end...

With pytz being deprecated and ZoneInfo being used for all Python 3.9 versions, have you looked at removing pytz in favor of ZoneInfo? 

I'm in the Eastern USA, currently on daylight savings time. Using pytz, the displayTZ in the main config.json won't work with 'EDT.' It returns a Google API error when running main.py because I'm pretty sure the API doesn't recognize 'EDT.' 'EST' works fine, but all my calendar events are one hour off.

**Comment by fdmarcin** [comment]
@pachieh Nope :) Once I got it working for myself (and later removed the
ChatGPT feature), I stopped.

For the timezone, try US/Eastern or US/New York, because pytz supports this
format:

- https://stackoverflow.com/a/13867305
- https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by pachieh** [comment]
@fdmarcin 

Yeah, tried those ('New York' 'New_York')... 

pytz.exceptions.UnknownTimeZoneError: 'US/New_York'

or when I use 'Eastern' or a few of the different available options in pytz like 'America/New_York'...

Traceback (most recent call last):
  File "/Users/brian/Desktop/MagInkDash-updated-main/main.py", line 60, in <module>
    allEventList = calModule.get_events(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brian/Desktop/MagInkDash-updated-main/gcal/gcal.py", line 76, in get_events
    calList[idx].append(event)
    ~~~~~~~^^^^^
IndexError: list index out of range

**Comment by pachieh** [comment]
For those interested and running into the same problem in the USA dealing with Daylight Savings Time in the main config.json file with displayTZ. I still don't fully understand why I had such issues using "America/New_York" but "EST" worked fine just one hour off. "EDT" didn't work at all. 

I fixed the IndexError referenced above by adding the following under gcal.py near the end under the multiday event check. Thanks to Gemini Pro for helping dig into the indexing problem, I ended up uploading a few of the python files and had it dig into any potential errors. It recommend this to prevent the code from trying to reference an index that doesn't exist.

Original code:
            elif idx >= 0:
                calList[idx].append(event)


Updated code:

            elif idx >= 0 and idx < len(calList):
                calList[idx].append(event)
